### PR TITLE
Fix notices in XmlPublisher for Risky tests + add typehints

### LINKED ISSUE #192: Risky test-case causes notice
When test is marked as risky (eg. id does not perform any assertions), notice is thrown from `TestStatusListener`:

```
Foo\BarTest> Notice: Undefined offset: 5 in /.../src/Listener/TestStatusListener.php on line 122
```

The same is for `Warning` test (ie. status is `BaseTestRunner::STATUS_WARNING`). 

Both of those cases should be mapped to Steward test results.

### PR DESCRIPTION
**Pull request by OndraM**
Fixes #192 and also adds typehints and other PHP 7 features as part of #162 .

### CODE REVIEW

File: src-tests/Listener/Fixtures/DummyPublisher.php [hunk 1]
```diff
@@ -8,21 +8,21 @@
 class DummyPublisher extends AbstractPublisher
 {
     public function publishResults(
-        $testCaseName,
-        $status,
-        $result = null,
-        \DateTimeInterface $startDate = null,
-        \DateTimeInterface $endDate = null
+        string $testCaseName,
```
Comment (jirinovak) [inline src-tests/Listener/Fixtures/DummyPublisher.php:11]: Why not add `declare(strict_types=1);`.

Same `ExceptionThrowingPublisher.php` and others.

Comment (OndraM) [reply src-tests/Listener/Fixtures/DummyPublisher.php:11]: Thanks, fixed
